name: danger

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled, edited]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

permissions:
  contents: read
  pull-requests: write
  
jobs:
  run-danger:
    runs-on: ubuntu-latest
    steps:
      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.0
          bundler-cache: true
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup gems
        run: |
          gem install bundler
          bundle config set clean true
          bundle config set path 'vendor/bundle'
          bundle install
      - name: danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: bundle exec danger --verbose